# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# no mountain and the 5-layer dots
CONFIG_NICE_VIEW_WIDGET_STATUS=n

# enable the standard ZMK vertical layer widget (prints your display-names)
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# battery percentage next to the battery icon
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# (WPM) tracker graph
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# show Bluetooth profile
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y